# Data Analysis Process 
###  1. Asking Question
####   2. Data Wrangling
       a. Gathering
            i. CSV files
            ii. APIs
            iii. Web Scraping
            iv. Databases
        b. Assessing Data
        c. Cleaning Data
####    3. Exploratory Data Analysis
####    4. Drawing Conclusion
####    5. Communicating Result

### 1. Data Wrangling 
        • Data Gathering 
        • Data Assessing 
        • Data Cleaning

## 1b. Data Assessing 
    In this step, the data is to be understood more deeply. Before Implementing methods to clean it, you will definitely need to have a better idea about what the data is about.

## Types of Unclean Data :
    ° There are 2 Kinds of unclean data.

#### • Dirty Data (Data with Quality issues): Dirty data, also known as low quality data. low quality data has content issues.
    ° Duplicated Data
    ° Missing data
    ° Corrupt Data
    ° Inaccurate Data

#### • Messy Data (Data with tidiness issues): Messy data, also known as untidy data. Untidy data has Structural issues. Tidy data has the following properties.
    ° Each variable forms a columns
    ° Each observation forms a row
    ° Each observation unit forms a table

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Datasets :-

patients = pd.read_csv("D:\LEARNING\patients.csv")
treatments = pd.read_csv("D:\LEARNING\\treatments.csv")
adverse_reactions = pd.read_csv("D:\LEARNING\\adverse_reactions.csv")
treatments_cut = pd.read_csv("D:\LEARNING\\treatments_cut.csv")

In [3]:
patients.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [4]:
treatments.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32

In [5]:
treatments_cut.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,jožka,resanovič,22u - 30u,-,7.56,7.22,0.34
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,NaN
2,alwin,svensson,36u - 39u,-,7.78,7.34,NaN
3,thể,lương,-,61u - 64u,7.64,7.22,0.92
4,amanda,ribeiro,36u - 44u,-,7.85,7.47,0.38

In [6]:
adverse_reactions.head()

  given_name     surname           adverse_reaction
0      berta  napolitani  injection site discomfort
1       lena        baer               hypoglycemia
2     joseph         day               hypoglycemia
3     flavia  fiorentino                      cough
4    manouck     wubbels          throat irritation

In [ ]:
# Data Assessing :-
    # 1. Write a summary for your data
    # 2. Write Columns descriptions (Tables)
    # 3. Write Add any additional Information

## Types of Assessment 
### There are 2 types of assessment styles
    • **Manual** -> Looking through the data manually in google sheets.
    • **Programmatic** -> By using pandas function such as info(), describe(), or sample().

### Steps in Assessment 
### There are 2 Steps involved in Assessment 
    • Discover
    • Document

In [7]:
# 1. expert data or manual assessment :-

with pd.ExcelWriter('clinical_trials.xlsx') as writer:
    patients.to_excel(writer, sheet_name='patients')
    treatments.to_excel(writer, sheet_name='treatments')
    treatments_cut.to_excel(writer, sheet_name='treatments_cut')
    adverse_reactions.to_excel(writer, sheet_name='adverse_reactions')

### Issues with the dataset

1. Dirty Data

  Table - `Patients`

    - patient_id = 9 has misspelled name 'Dsvid' instead of David `accuracy`
    - state col sometimes contain full name and some times abbrivietation `consistency`
    - zip code col has entries with 4 digit `validity`
    - data missing for 12 patients in address,city,	state,zip_code	,country,	contact `completion`
    - incorrect data type assigned to sex, zip code, birthdate `validity`
    - duplicate entries by the name of John Doe `accuracy`
    - one patient has weight = 48 pounds `accuracy`
    - one patient has height = 27 inches `accuracy`

  Table - `Treatments` & `Treatments_cut`

    - given_name and surname col is is all lower case `consistency`
    - remove u from Auralin and Novadra cols `validity`
    - '-' in novadra and Auralin col treated as nan `validity`
    - missing values in hba1c_change col `completion`
    - 1 duplicate entry by the name Joseph day `accuracy`
    - in hba1c_change 9 instead of 4 `accuracy`

  Table - `Adverse_reactions`

    - given_name and surname are all in lower case `consistency`

2. Messy Data

  Table - `Patients`

    - contact col contains both phone and email

  Table - `Treatments` & `Treatments_cut`

    - Auralin and Novadra col should be split into 2 cols start and end dose
    - merge both the tables

  Table - `Adverse_reactions`

    - This table should not exist independently

## *Automatic Assessment*
    **head and tail**
    **sample**
    **info**
    **isnull**
    **duplicated**
    **describe**


# *Note -> Assessing Data is an Iterative Process.*

In [15]:
# Dataset: Patients 

patients.head()
patients.sample(5)
patients.info()
patients.describe()
patients.isnull()
patients.duplicated()


# do this on every dataset for better clarity.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       491 non-null    object
 5   city          491 non-null    object
 6   state         491 non-null    object
 7   zip_code      491 non-null    float64
 8   country       491 non-null    object
 9   contact       491 non-null    object
 10  birthdate     503 non-null    object
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(3), int64(2), object(9)
memory usage: 55.1+ KB

0      False
1      False
2      False
3      False
4      False
       ...
498    False
499    False
500    False
501    False
502    False
Length: 503, dtype: bool